-- Bind key
-- Inside
--
-- cs"'
--
-- cs'<q>
--
-- To remove the delimiters entirely, press ds".
--
-- press cst" to get
--
-- Now with the cursor on "Hello", press ysiw] (iw is a text object).
--
-- Let's make that braces and add some space (use } instead of { for no space): cs]{
--
-- Now wrap the entire line in parentheses with yssb or yss).
--
-- Revert to the original text: ds{ds)
--
-- Emphasize hello: ysiw<em>
--
-- Finally, let's try out visual mode. Press a capital V (for linewise visual mode) followed by S<p class="important">.
